tradestuff/config/routes.rb
Tradestuff::Application.routes.draw do
    get 'auth/:provider/callback', to: 'sessions#create'
    get 'auth/failure', to: redirect('/')
    get 'signout', to: 'sessions#destroy', as: 'signout'
    get 'home/users_account'
    get 'home/item_page'
    get 'home/item1'
    get 'home/item2'
    get 'home/item3'

    
    resources :sessions, only: [:create, :destroy]
    resource :home, only: [:show]

    root to: "home#show"
    
    
end

#'userinfo#show1' 'home#users_account'

tradestuff/app/models/concerns/tradestuff_item.rb
class Item < ActiveRecord::Base
end

tradestuff/app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessor :item_id, :item_name, :item_desc
  
end

tradestuff/app/models/item_list.rb
class Item_list < ActiveRecord::Base
  attr_accessor :item_id, :item_id, :uid, :quantity, :condition, :photo, :list_type
end

tradestuff/app/models/userinfo.rb
class Userinfo < ActiveRecord::Base
  attr_accessor :uid, :fname, :lname, :email, :phone, :address, :city, :zip, :state, :country
end

tradestuff/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

tradestuff/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
    @items = Item.all
  end
  def users_account
   @userinfos = Userinfo.all
  end
  

  def userinfo_params
    params.require(:user).permit(:uid, :fname, :lname, :email, :phone, :address, :city, :zip, :state, :country)
  end
  
  def item_page
  end
  
  def item1
  end
  
  def item2
  end
  
  def item3
  end

  
  def index
   @userinfos = Userinfo.all
  end
  def create
    @userinfo = Userinfo.create!(params[:userinfo])
    flash[:notice] = "#{@userinfo.title} was successfully created."
  end

end

tradestuff/app/controllers/userinfo_controller.rb
class UserinfoController < ApplicationController

  def userinfo_params
    params.require(:user).permit(:uid, :fname, :lname, :email, :phone, :address, :city, :zip, :state, :country)
  end

  def show
    id = params[:uid] # retrieve user ID from URI route
    @userinfo = Userinfo.find(uid) # look up user by unique ID
    # will render app/views/movies/show.<extension> by default
  end
  
  def index
   @userinfos = Userinfo.all
  end
  def create
    @userinfo = Userinfo.create!(params[:userinfo])
    flash[:notice] = "#{@userinfo.title} was successfully created."
  end


end

tradestuff/app/views/home/item1.html.haml
%h1 Items

/= form_tag alll_path do
/- @items.each do |it|
%div.itemcard
  %div.ipic= image_tag "Sammy.jpg", width: "175px", height: "120px"
  %div.iuser User: Jordan Mullan
  %div.iquan Qty: 18
  %div.iname Sandwich
  %div.idesc Description: Decent sized sandwich. roughly six inches. made with meats, vegetables and condiments of your choice.


/- = link_to 'Add new movie', new_movie_path

tradestuff/app/views/home/item2.html.haml
%h1 Items

/= form_tag alll_path do
/- @items.each do |it|
%div.itemcard
  %div.ipic= image_tag "Phillips.jpg", width: "175px", height: "120px"
  %div.iuser User: Jordan Mullan
  %div.iquan Qty: 1
  %div.iname Phillips head screwdriver
  %div.idesc Description: Large screwdriver with a + shaped head used to screw in screws.


/- = link_to 'Add new movie', new_movie_path

tradestuff/app/views/home/item3.html.haml
%h1 Items

/= form_tag alll_path do
/- @items.each do |it|
%div.itemcard
  %div.ipic= image_tag "Flathead.jpg", width: "175px", height: "120px"
  %div.iuser User: Jordan Mullan
  %div.iquan Qty: 1
  %div.iname Flathead screwdriver
  %div.idesc Description: Large screwdriver with a flat head used to screw in screws.


/- = link_to 'Add new movie', new_movie_path

tradestuff/app/views/home/item_page.html.haml
%h1 Items

/= form_tag alll_path do
/- @items.each do |it|
%div.itemcard
  %div.ipic= image_tag "Hammer.jpg", width: "175px", height: "120px"
  %div.iuser User: Jordan Mullan
  %div.iquan Qty: 3
  %div.iname  Hammer
  %div.idesc Description: Small tool used to apply small blows to nails and other objects.


/- = link_to 'Add new movie', new_movie_path

tradestuff/app/views/home/my_account.html.haml
%h1 All users

= form_tag my_account do
%h2 Details about #{@userinfo.fname}

%table#movies
  %thead
    %tr
      %th ID
      %th First name
      %th Last name
      %th email
      %th phone
      %th address
      %th city
      %th state
      %th zip
      %th country
  %tbody
      %tr
        %td= userinfo.uid 
        %td= userinfo.fname
        %td= userinfo.lname
        %td= userinfo.email
        %td= userinfo.phone
        %td= userinfo.address
        %td= userinfo.city
        %td= userinfo.state
        %td= userinfo.zip
        %td= userinfo.country

/- = link_to 'edit', my_account_path_edit


/- have list
%table#movies
  %thead
    %tr
      %th Item
      %th Quantity
  %tbody
    - @user_item_list.each do |item|
      %tr
        %td= item.items.name
        %td=item.quantity
      
      
/- want list

tradestuff/app/views/home/myaccount.html.haml
-#  This file is app/views/movies/index.html.haml
%h1 My Account

%table#userinfos
  %thead
    %tr
      %th Email
      %th Phone Number
      %th Address
      %th City
      %th State
      %th Zip
      %th Country
      
      


  %tbody
    - @userinfos.each do |user|
      %tr
        %td= user.email 
        %td= user.phone
        %td= user.address
        %td= user.city
        %td= user.state
        %td= user.zip
        %td= user.country
-#        %td= link_to "More about #{movie.title}", movie_path(movie)

= link_to 'Edit User Information', edit_userinfo_path

tradestuff/app/views/home/show.html.haml
%h1 Tradestuff

Add stuff to this page!
%body
%div.itp= link_to image_tag("Hammer.jpg", width: "150px", height: "100px"), home_item_page_path
%div.itpd= link_to "Hammer", home_item_page_path

%div.itp1= link_to image_tag("Sammy.jpg", width: "150px", height: "100px"), home_item1_path
%div.itpd1= link_to "Sandwich", home_item1_path

%div.itp2= link_to image_tag("Phillips.jpg", width: "150px", height: "100px"), home_item2_path
%div.itpd2= link_to "Phillips head", home_item2_path

%div.itp3= link_to image_tag("Flathead.jpg", width: "150px", height: "100px"), home_item3_path
%div.itpd3= link_to "Flat head", home_item3_path

tradestuff/app/views/home/users_account.html.haml
-#  This file is app/views/movies/index.html.haml
%h1 All Users

/= form_tag alll_path do

%table#users
  %thead
    %tr
      %th ID
<<<<<<< HEAD
      %th Rating
      %th email
      %th More info
      %th trading
  %tbody
    - @userinfos.each do |user|
      %tr
        %td= user.uid 
        %td= user.fname
        %td= user.email
        %td more(will be a link to users info)
        %td trade(will be a link to trade)
=======
      %th Name
      %th Last Name
      %th Email
      %th Phone
      %th Address
      %th City
      %th State
      %th Zip
      %th Country
      %th Trading
      
      Trade History
  %tbody
    - @userinfos.each do |user|
      %tr
        %td= 1
        %td= user.fname = 'Adam'
        %td= user.lname = 'Fleischhacker'
        %td= user.email = 'fake@email.com'
        %td= user.phone = '098-765-4321'
        %td= user.address = ' 456 Not Real Rd'
        %td= user.city = 'St. Paul'
        %td= user.state = 'MN'
        %td= user.zip = '55117'
        %td= user.country = 'United States'
        %td= link_to "More about #{user.uid}", root_path
      // %tr
      //   %td= 2
      //   %td= user.fname = 'Jordan'
      //   %td= user.lname = 'Mullan'
      //   %td= user.email = 'jmullan@gmail.com'
      //   %td= user.phone = '651-456-7890'
      //   %td= user.address = '123 Fake St.'
      //   %td= user.city = 'Mankato'
      //   %td= user.state = 'MN'
      //   %td= user.zip = '56001'
      //   %td= user.country = 'United States'
      //   %td= link_to "More about #{user.uid}", root_path
      // %tr
      //   %td= 3
      //   %td= user.fname = 'Nick'
      //   %td= user.lname = 'Burr'
      //   %td= user.email = 'Nb@gmail.com'
      //   %td= user.phone = '651-346-9046'
      //   %td= user.address = '235 Skipper Ln.'
      //   %td= user.city = 'Owatonna'
      //   %td= user.state = 'MN'
      //   %td= user.zip = '56789'
      //   %td= user.country = 'United States'
      //   %td= link_to "More about #{user.uid}", root_path
      // %tr
      //   %td= 4
      //   %td= user.fname = 'Cristian'
      //   %td= user.lname = 'Gonzalez'
      //   %td= user.email = 'Cgonn@gmail.com'
      //   %td= user.phone = '651-456-5774'
      //   %td= user.address = '123 Fake St.'
      //   %td= user.city = 'Mankato'
      //   %td= user.state = 'MN'
      //   %td= user.zip = '56001'
      //   %td= user.country = 'United States'
      //   %td= link_to "More about #{user.uid}", root_path
        
>>>>>>> 3c648696aaeb64cd2cf30a19bdf454062054a642

/- = link_to 'Add new movie', new_movie_path
%p
  = link_to 'Accounts', home_users_account_path 
  = link_to 'Home', root_path

tradestuff/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TradeStuff</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    
    <div class="logo">
    <%= link_to image_tag("logo.png", width: '762px'), root_path %>
    </div>
    
    <div class="sidebar">
    <%= image_tag("Sidebar.png") %>
    </div>
    
    <div class="myAccountButton">
    <% if current_user %>
    <%= link_to image_tag("MyAccount.png"), home_users_account_path %>
    <% else %>
    <%= link_to image_tag("MyAccount.png"), "/auth/facebook", id: "sign_in" %>
    <% end %>
    </div>
    
    <div class="searchButton">
    <%= link_to image_tag("Search.png"), home_item_page_path %>
    </div>
    
    <div class="tradesButton">
    <%= image_tag("Trades.png") %>
    </div>
    
    <div class="haveButton">
    <%= image_tag("Have.png") %>
    </div>
    
    <div class="wantButton">
    <%= image_tag("Want.png") %>
    </div>
    
    <div class="user_nav">
      <% if current_user %>
        Signed in as <strong><%= current_user.name %></strong>!
        <%= link_to " Sign out", signout_path, id: "sign_out" %>
      <% else %>
        <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>